export const AppActionTypes = {
  APP_LOADING: "APP_LOADING",
};

export const AuthActionTypes = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  SIGNUP: "SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  SET_AUTH_LOADER: "SET_AUTH_LOADER",
};

export const RestaurantActionTypes = {
  GET_RESTAURANTS: "GET_RESTAURANTS",
  GET_SAVED_RESTAURANTS: "GET_SAVED_RESTAURANTS",
  GET_RESTAURANTS_SUCCESS: "GET_RESTAURANTS_SUCCESS",

  SAVE_RESTAURANT: "SAVE_RESTAURANT",

  REMOVE_SAVED_RESTAURANT: "REMOVE_SAVED_RESTAURANT",
  REMOVE_SAVED_RESTAURANT_SUCCESS: "REMOVE_SAVED_RESTAURANT_SUCCESS",

  SET_RESTAURANT_LOADER: "SET_RESTAURANT_LOADER",
};

export const CollectionActionTypes = {
  CREATE_COLLECTION: "CREATE_COLLECTION",
  GET_COLLECTIONS: "GET_COLLECTIONS",
  GET_COLLECTIONS_SUCCESS: "GET_COLLECTIONS_SUCCESS",
  GET_COLLECTION_BY_ID: "GET_COLLECTION_BY_ID",
  GET_COLLECTION_BY_ID_SUCCESS: "GET_COLLECTION_BY_ID_SUCCESS",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",
  DELETE_COLLECTION: "DELETE_COLLECTION",
  DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",

  SET_COLLECTION_LOADER: "SET_COLLECTION_LOADER",
};
