export const AppActionTypes = {
  APP_LOADING: "APP_LOADING",
};

export const AuthActionTypes = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  SIGNUP: "SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  SET_AUTH_LOADER: "SET_AUTH_LOADER",
};

export const RestaurantActionTypes = {
  GET_RESTAURANTS: "GET_RESTAURANTS",
  GET_RESTAURANTS_SUCCESS: "GET_RESTAURANTS_SUCCESS",

  SET_RESTAURANT_LOADER: "SET_RESTAURANT_LOADER",
};
